/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthsRouteImport } from './routes/auths'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedVendorRouteRouteImport } from './routes/_authenticated/vendor/route'
import { Route as AuthenticatedVendorIndexRouteImport } from './routes/_authenticated/vendor/index'
import { Route as AuthenticatedVendorSettingsRouteImport } from './routes/_authenticated/vendor/settings'
import { Route as AuthenticatedVendorPrepRouteImport } from './routes/_authenticated/vendor/prep'
import { Route as AuthenticatedVendorMenuRouteImport } from './routes/_authenticated/vendor/menu'
import { Route as AuthenticatedVendorRestaurantsCreateIndexRouteImport } from './routes/_authenticated/vendor/restaurants/create/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthsRoute = AuthsRouteImport.update({
  id: '/auths',
  path: '/auths',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVendorRouteRoute =
  AuthenticatedVendorRouteRouteImport.update({
    id: '/vendor',
    path: '/vendor',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedVendorIndexRoute =
  AuthenticatedVendorIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedVendorRouteRoute,
  } as any)
const AuthenticatedVendorSettingsRoute =
  AuthenticatedVendorSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedVendorRouteRoute,
  } as any)
const AuthenticatedVendorPrepRoute = AuthenticatedVendorPrepRouteImport.update({
  id: '/prep',
  path: '/prep',
  getParentRoute: () => AuthenticatedVendorRouteRoute,
} as any)
const AuthenticatedVendorMenuRoute = AuthenticatedVendorMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AuthenticatedVendorRouteRoute,
} as any)
const AuthenticatedVendorRestaurantsCreateIndexRoute =
  AuthenticatedVendorRestaurantsCreateIndexRouteImport.update({
    id: '/restaurants/create/',
    path: '/restaurants/create/',
    getParentRoute: () => AuthenticatedVendorRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auths': typeof AuthsRoute
  '/login': typeof LoginRoute
  '/vendor': typeof AuthenticatedVendorRouteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/vendor/menu': typeof AuthenticatedVendorMenuRoute
  '/vendor/prep': typeof AuthenticatedVendorPrepRoute
  '/vendor/settings': typeof AuthenticatedVendorSettingsRoute
  '/vendor/': typeof AuthenticatedVendorIndexRoute
  '/vendor/restaurants/create': typeof AuthenticatedVendorRestaurantsCreateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auths': typeof AuthsRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/vendor/menu': typeof AuthenticatedVendorMenuRoute
  '/vendor/prep': typeof AuthenticatedVendorPrepRoute
  '/vendor/settings': typeof AuthenticatedVendorSettingsRoute
  '/vendor': typeof AuthenticatedVendorIndexRoute
  '/vendor/restaurants/create': typeof AuthenticatedVendorRestaurantsCreateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auths': typeof AuthsRoute
  '/login': typeof LoginRoute
  '/_authenticated/vendor': typeof AuthenticatedVendorRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/vendor/menu': typeof AuthenticatedVendorMenuRoute
  '/_authenticated/vendor/prep': typeof AuthenticatedVendorPrepRoute
  '/_authenticated/vendor/settings': typeof AuthenticatedVendorSettingsRoute
  '/_authenticated/vendor/': typeof AuthenticatedVendorIndexRoute
  '/_authenticated/vendor/restaurants/create/': typeof AuthenticatedVendorRestaurantsCreateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auths'
    | '/login'
    | '/vendor'
    | '/dashboard'
    | '/vendor/menu'
    | '/vendor/prep'
    | '/vendor/settings'
    | '/vendor/'
    | '/vendor/restaurants/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auths'
    | '/login'
    | '/dashboard'
    | '/vendor/menu'
    | '/vendor/prep'
    | '/vendor/settings'
    | '/vendor'
    | '/vendor/restaurants/create'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auths'
    | '/login'
    | '/_authenticated/vendor'
    | '/_authenticated/dashboard'
    | '/_authenticated/vendor/menu'
    | '/_authenticated/vendor/prep'
    | '/_authenticated/vendor/settings'
    | '/_authenticated/vendor/'
    | '/_authenticated/vendor/restaurants/create/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthsRoute: typeof AuthsRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auths': {
      id: '/auths'
      path: '/auths'
      fullPath: '/auths'
      preLoaderRoute: typeof AuthsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vendor': {
      id: '/_authenticated/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof AuthenticatedVendorRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vendor/': {
      id: '/_authenticated/vendor/'
      path: '/'
      fullPath: '/vendor/'
      preLoaderRoute: typeof AuthenticatedVendorIndexRouteImport
      parentRoute: typeof AuthenticatedVendorRouteRoute
    }
    '/_authenticated/vendor/settings': {
      id: '/_authenticated/vendor/settings'
      path: '/settings'
      fullPath: '/vendor/settings'
      preLoaderRoute: typeof AuthenticatedVendorSettingsRouteImport
      parentRoute: typeof AuthenticatedVendorRouteRoute
    }
    '/_authenticated/vendor/prep': {
      id: '/_authenticated/vendor/prep'
      path: '/prep'
      fullPath: '/vendor/prep'
      preLoaderRoute: typeof AuthenticatedVendorPrepRouteImport
      parentRoute: typeof AuthenticatedVendorRouteRoute
    }
    '/_authenticated/vendor/menu': {
      id: '/_authenticated/vendor/menu'
      path: '/menu'
      fullPath: '/vendor/menu'
      preLoaderRoute: typeof AuthenticatedVendorMenuRouteImport
      parentRoute: typeof AuthenticatedVendorRouteRoute
    }
    '/_authenticated/vendor/restaurants/create/': {
      id: '/_authenticated/vendor/restaurants/create/'
      path: '/restaurants/create'
      fullPath: '/vendor/restaurants/create'
      preLoaderRoute: typeof AuthenticatedVendorRestaurantsCreateIndexRouteImport
      parentRoute: typeof AuthenticatedVendorRouteRoute
    }
  }
}

interface AuthenticatedVendorRouteRouteChildren {
  AuthenticatedVendorMenuRoute: typeof AuthenticatedVendorMenuRoute
  AuthenticatedVendorPrepRoute: typeof AuthenticatedVendorPrepRoute
  AuthenticatedVendorSettingsRoute: typeof AuthenticatedVendorSettingsRoute
  AuthenticatedVendorIndexRoute: typeof AuthenticatedVendorIndexRoute
  AuthenticatedVendorRestaurantsCreateIndexRoute: typeof AuthenticatedVendorRestaurantsCreateIndexRoute
}

const AuthenticatedVendorRouteRouteChildren: AuthenticatedVendorRouteRouteChildren =
  {
    AuthenticatedVendorMenuRoute: AuthenticatedVendorMenuRoute,
    AuthenticatedVendorPrepRoute: AuthenticatedVendorPrepRoute,
    AuthenticatedVendorSettingsRoute: AuthenticatedVendorSettingsRoute,
    AuthenticatedVendorIndexRoute: AuthenticatedVendorIndexRoute,
    AuthenticatedVendorRestaurantsCreateIndexRoute:
      AuthenticatedVendorRestaurantsCreateIndexRoute,
  }

const AuthenticatedVendorRouteRouteWithChildren =
  AuthenticatedVendorRouteRoute._addFileChildren(
    AuthenticatedVendorRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedVendorRouteRoute: typeof AuthenticatedVendorRouteRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedVendorRouteRoute: AuthenticatedVendorRouteRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthsRoute: AuthsRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
